apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ringo-artist
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: ringo-artist
    spec:
      containers:
      - name: ringo-artist
        image: mjsdemoreg.azurecr.io/ringo-artist:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ringo-artist
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: ringo-artist